### ISSUE TITLE
RAML 1.0 support

### ISSUE THREAD

**Issue by lyndseypadget** [mulesoft-labs/node-raml-validate#3]
AFAIK, [API Workbench](https://github.com/mulesoft/api-workbench) is currently the only way to validate my 1.0 RAML.  The problems with that are: 1) It is cripplingly slow and 2) It's only useful for humans, not automated systems.  Is there a plan to update node-raml-validate to support 1.0 RAML?  If not, what is API Workbench using to validate under the covers and can it be exposed via command line?

**Comment by blakeembrey** [comment]
It should support RAML 1.0, but only the older types - not the new type system which requires a new implementation. I believe the type system work from API Workbench should be open sourced at some point.

**Comment by sichvoge** [comment]
I guess the question from my side would be if you need to validate a complete RAML file or just named parameters?

**Comment by wjagodfrey** [comment]
I need the new type system, and currently there is no solution for node that I can find implementing RAML 1.0

**Comment by sichvoge** [comment]
What about https://www.npmjs.com/package/raml-1-parser?

**Comment by blakeembrey** [comment]
@sichvoge The parser is not related to creating a validation of the type system - this module was used for validating HTTP headers, query parameters, form data requests, etc. against RAML 0.8.

**Comment by sichvoge** [comment]
Hence my question if @wjagodfrey is more interested into validating named parameters or a RAML 1.0 definition. It is not fully clear to me.

**Comment by lyndseypadget** [comment]
I need to validate an entire 1.0 RAML definition (meaning, the top-level RAML and all of its referenced files).  Every time someone on my team updates the definition, I need an automated test to ensure they did not introduce malformed/invalid RAML.

**Comment by wjagodfrey** [comment]
@sichvoge my exact usecase was a need for something similar to JSON schema in RAML 0.8, but composable from many schemas, and able to take `<parameters>`

Really, this is just traits for queryParameters, but being used in JSON request bodies instead. I had a feeling that RAML 1.0 Data Types would sort me out.

Have moved onto another solution for now.
